Public Class Form1

    Private A As Integer
    Private B As Integer

    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        If A = 0 Then
            Button1.BackColor = Color.White   '0
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.Crimson
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.Crimson
            Button11.BackColor = Color.Crimson
            Button12.BackColor = Color.White
            Button13.BackColor = Color.White
            Button14.BackColor = Color.White
            Button15.BackColor = Color.Crimson
            Button16.BackColor = Color.Crimson
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.White
            Button20.BackColor = Color.Crimson
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 1



        ElseIf A = 1 Then
            Button1.BackColor = Color.White   '1
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.White
            Button5.BackColor = Color.White
            Button6.BackColor = Color.White
            Button7.BackColor = Color.White
            Button8.BackColor = Color.Crimson
            Button9.BackColor = Color.White
            Button10.BackColor = Color.White
            Button11.BackColor = Color.White
            Button12.BackColor = Color.White
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.White
            Button15.BackColor = Color.White
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.Crimson
            Button19.BackColor = Color.White
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 2

        ElseIf A = 2 Then
            Button1.BackColor = Color.White   '2
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.White
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.Crimson
            Button11.BackColor = Color.White
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.White
            Button16.BackColor = Color.White
            Button17.BackColor = Color.Crimson
            Button18.BackColor = Color.White
            Button19.BackColor = Color.White
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.Crimson
            A = 3

        ElseIf A = 3 Then
            Button1.BackColor = Color.Crimson   '3
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.White
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.Crimson
            Button11.BackColor = Color.White
            Button12.BackColor = Color.White
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.White
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.White
            Button20.BackColor = Color.Crimson
            Button21.BackColor = Color.Crimson
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 4

        ElseIf A = 4 Then
            Button1.BackColor = Color.White   '4
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.White
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.White
            Button7.BackColor = Color.Crimson
            Button8.BackColor = Color.White
            Button9.BackColor = Color.Crimson
            Button10.BackColor = Color.White
            Button11.BackColor = Color.White
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.Crimson
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.Crimson
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.White
            Button23.BackColor = Color.White
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 5

        ElseIf A = 5 Then
            Button1.BackColor = Color.Crimson   '5
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.Crimson
            Button6.BackColor = Color.Crimson
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.White
            Button11.BackColor = Color.Crimson
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.Crimson
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.White
            Button20.BackColor = Color.Crimson
            Button21.BackColor = Color.Crimson
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.Crimson
            A = 6

        ElseIf A = 6 Then
            Button1.BackColor = Color.White   '6
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.Crimson
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.White
            Button11.BackColor = Color.Crimson
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.White
            Button16.BackColor = Color.Crimson
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.Crimson
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 7

        ElseIf A = 7 Then
            Button1.BackColor = Color.Crimson   '7
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.Crimson
            Button6.BackColor = Color.White
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.Crimson
            Button11.BackColor = Color.White
            Button12.BackColor = Color.White
            Button13.BackColor = Color.White
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.White
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.Crimson
            Button19.BackColor = Color.White
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.White
            Button24.BackColor = Color.White
            Button25.BackColor = Color.White
            A = 8

        ElseIf A = 8 Then
            Button1.BackColor = Color.Crimson   '8
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.Crimson
            Button6.BackColor = Color.Crimson
            Button7.BackColor = Color.White
            Button8.BackColor = Color.White
            Button9.BackColor = Color.White
            Button10.BackColor = Color.Crimson
            Button11.BackColor = Color.Crimson
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.Crimson
            Button16.BackColor = Color.Crimson
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.White
            Button20.BackColor = Color.Crimson
            Button21.BackColor = Color.Crimson
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.Crimson
            A = 9

        ElseIf A = 9 Then
            Button1.BackColor = Color.White   '9
            Button2.BackColor = Color.Crimson
            Button3.BackColor = Color.Crimson
            Button4.BackColor = Color.Crimson
            Button5.BackColor = Color.White
            Button6.BackColor = Color.White
            Button7.BackColor = Color.Crimson
            Button8.BackColor = Color.White
            Button9.BackColor = Color.Crimson
            Button10.BackColor = Color.White
            Button11.BackColor = Color.White
            Button12.BackColor = Color.Crimson
            Button13.BackColor = Color.Crimson
            Button14.BackColor = Color.Crimson
            Button15.BackColor = Color.White
            Button16.BackColor = Color.White
            Button17.BackColor = Color.White
            Button18.BackColor = Color.White
            Button19.BackColor = Color.Crimson
            Button20.BackColor = Color.White
            Button21.BackColor = Color.White
            Button22.BackColor = Color.Crimson
            Button23.BackColor = Color.Crimson
            Button24.BackColor = Color.Crimson
            Button25.BackColor = Color.White
            A = 0
        End If
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        A = 0
        B = -1


        Timer1.Enabled = True
        Timer1.Start()
        Timer1.Interval = 1000

    End Sub
End Class
